// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TPHunter.WebServices.Shared.MainData.Data;

namespace TPHunter.WebServices.Shared.MainData.Data.Migrations
{
    [DbContext(typeof(MainDataContext))]
    [Migration("20221204134436_AddPatentModelBulletinDate")]
    partial class AddPatentModelBulletinDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("AttorneyCompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyCompanyId");

                    b.ToTable("Attorneys");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.AttorneyCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AttorneyCompanies");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Design", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("AttorneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BulletinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BulletinNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DesignStatusId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyId");

                    b.HasIndex("DesignStatusId");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DesignPriortyCountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DesignProductPriortyTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExhibitionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExhibitionName")
                        .HasColumnType("text");

                    b.Property<string>("ExhibitionPlace")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstExhibitionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProductApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PriortyApplicationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PriortyDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.HasIndex("DesignPriortyCountryId");

                    b.HasIndex("DesignProductPriortyTypeId");

                    b.ToTable("DesignProducts");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductClassesRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocarnoClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesignProductId");

                    b.HasIndex("LocarnoClassId");

                    b.ToTable("DesignProductClassesRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignProductId");

                    b.ToTable("DesignProductImages");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DesignProductPriortyCountries");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DesignProductPriortyTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DesignStatuses");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DesignTransactionDescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DesignTransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.HasIndex("DesignTransactionDescriptionId");

                    b.HasIndex("DesignTransactionTypeId");

                    b.ToTable("DesignTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DesignTransactionDescriptionDetailId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignTransactionDescriptionDetailId");

                    b.ToTable("DesignTransactionDescriptions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescriptionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DesignTransactionDescriptionDetails");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DesignTransactionTypeDetailId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesignTransactionTypeDetailId");

                    b.ToTable("DesignTransactionTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionTypeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DesignTransactionTypeDetails");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Designer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignerRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DesignerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.HasIndex("DesignerId");

                    b.ToTable("DesignerRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Holder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HolderCode")
                        .HasColumnType("text");

                    b.Property<string>("HolderName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Holders");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.HolderRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DataId")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<Guid>("HolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.ToTable("HolderRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Inventor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InventorCode")
                        .HasColumnType("text");

                    b.Property<string>("InventorName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Inventors");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.InventorRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InventorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventorId");

                    b.HasIndex("PatentId");

                    b.ToTable("InventorRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.LocarnoClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LocarnoClasses");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("AttorneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BulletinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("EpcApplicationNumber")
                        .HasColumnType("text");

                    b.Property<string>("EpcPublishNumber")
                        .HasColumnType("text");

                    b.Property<string>("InventionSummary")
                        .HasColumnType("text");

                    b.Property<string>("InventionTitle")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PatentApplicationTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatentProtectionTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PctApplicationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PctPublishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PctPublishNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyId");

                    b.HasIndex("PatentApplicationTypeId");

                    b.HasIndex("PatentProtectionTypeId");

                    b.ToTable("Patents");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentApplicationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatentApplicationTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("PatentClassTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatentClassTypeId");

                    b.ToTable("PatentClasses");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClassRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatentClassId");

                    b.HasIndex("PatentId");

                    b.ToTable("PatentClassRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatentClassTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Queue")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.ToTable("PatentPayments");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPdf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PdfType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.ToTable("PatentPdFs");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPriorty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatentPriortyCountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PriortyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PriortyNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.HasIndex("PatentPriortyCountryId");

                    b.ToTable("PatentPriorties");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPriortyCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PatentPriortyCountries");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentProtectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatentProtectionTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatentPublicationDescriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.HasIndex("PatentPublicationDescriptionId");

                    b.ToTable("PatentPublications");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPublicationDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PatentPublicationDescriptions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatentTransactionNameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.HasIndex("PatentTransactionNameId");

                    b.ToTable("PatentTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentTransactionName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Transaction")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatentTransactionNames");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("AttorneyId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("Classes")
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeclareBullettinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeclareBullettinNumber")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("InternationalRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProtectionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RegistrationBullettinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationBullettinNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("TradeMarkDecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TradeMarkPriortyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TradeMarkStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TradeMarkTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttorneyId");

                    b.HasIndex("TradeMarkDecisionId");

                    b.HasIndex("TradeMarkPriortyId");

                    b.HasIndex("TradeMarkStatusId");

                    b.HasIndex("TradeMarkTypeId");

                    b.ToTable("TradeMarks");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TradeMarkDecisionReasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeMarkDecisionReasonId");

                    b.ToTable("TradeMarkDecisions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecisionReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkDecisionReasons");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriorty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TradeMarkPriortyCountryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeMarkPriortyCountryId");

                    b.ToTable("TradeMarkPriorties");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriortyCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkPriortyCountries");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<Guid>("TradeMarkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeMarkId");

                    b.ToTable("TradeMarkServices");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkStatuses");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("TradeMarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TradeMarkTransactionDescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TradeMarkTransactionNameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradeMarkTransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TradeMarkId");

                    b.HasIndex("TradeMarkTransactionDescriptionId");

                    b.HasIndex("TradeMarkTransactionNameId");

                    b.HasIndex("TradeMarkTransactionTypeId");

                    b.ToTable("TradeMarkTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkTransactionDescriptions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutMark")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("TradeMarkTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeMarkTransactionId");

                    b.ToTable("TradeMarkTransactionDetails");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Transaction")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkTransactionNames");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkTransactionTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeMarkTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.AttorneyCompany", "AttorneyCompany")
                        .WithMany("Attorneys")
                        .HasForeignKey("AttorneyCompanyId");

                    b.Navigation("AttorneyCompany");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Design", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", "Attorney")
                        .WithMany("Designs")
                        .HasForeignKey("AttorneyId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignStatus", "DesignStatus")
                        .WithMany("Designs")
                        .HasForeignKey("DesignStatusId");

                    b.Navigation("Attorney");

                    b.Navigation("DesignStatus");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProduct", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Design", "Design")
                        .WithMany("DesignProducts")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyCountry", "DesignPriortyCountry")
                        .WithMany("DesignProducts")
                        .HasForeignKey("DesignPriortyCountryId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyType", "DesignProductPriortyType")
                        .WithMany("DesignProducts")
                        .HasForeignKey("DesignProductPriortyTypeId");

                    b.Navigation("Design");

                    b.Navigation("DesignPriortyCountry");

                    b.Navigation("DesignProductPriortyType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductClassesRelation", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProduct", "DesignProduct")
                        .WithMany("DesignProductClassesRelations")
                        .HasForeignKey("DesignProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.LocarnoClass", "LocarnoClass")
                        .WithMany("DesignProductClassesRelations")
                        .HasForeignKey("LocarnoClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignProduct");

                    b.Navigation("LocarnoClass");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductImage", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProduct", "DesignProduct")
                        .WithMany("DesignProductImages")
                        .HasForeignKey("DesignProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignProduct");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransaction", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Design", "Design")
                        .WithMany("DesignTransactions")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescription", "DesignTransactionDescription")
                        .WithMany("DesignTransactions")
                        .HasForeignKey("DesignTransactionDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionType", "DesignTransactionType")
                        .WithMany("DesignTransactions")
                        .HasForeignKey("DesignTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("DesignTransactionDescription");

                    b.Navigation("DesignTransactionType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescription", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescriptionDetail", "DesignTransactionDescriptionDetail")
                        .WithMany("DesignTransactionDescriptions")
                        .HasForeignKey("DesignTransactionDescriptionDetailId");

                    b.Navigation("DesignTransactionDescriptionDetail");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionType", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionTypeDetail", "DesignTransactionTypeDetail")
                        .WithMany("DesignTransactionTypes")
                        .HasForeignKey("DesignTransactionTypeDetailId");

                    b.Navigation("DesignTransactionTypeDetail");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignerRelation", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Design", "Design")
                        .WithMany("DesignerRelations")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Designer", "Designer")
                        .WithMany("DesignerRelations")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.HolderRelation", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Holder", "Holder")
                        .WithMany("HolderRelations")
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.InventorRelation", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Inventor", "Inventor")
                        .WithMany("InventorRelations")
                        .HasForeignKey("InventorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("InventorRelations")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventor");

                    b.Navigation("Patent");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", "Attorney")
                        .WithMany("Patents")
                        .HasForeignKey("AttorneyId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentApplicationType", "PatentApplicationType")
                        .WithMany("Patents")
                        .HasForeignKey("PatentApplicationTypeId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentProtectionType", "PatentProtectionType")
                        .WithMany("Patents")
                        .HasForeignKey("PatentProtectionTypeId");

                    b.Navigation("Attorney");

                    b.Navigation("PatentApplicationType");

                    b.Navigation("PatentProtectionType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClass", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClassType", "PatentClassType")
                        .WithMany("PatentClasses")
                        .HasForeignKey("PatentClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatentClassType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClassRelation", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClass", "PatentClass")
                        .WithMany("PatentClassRelations")
                        .HasForeignKey("PatentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentClassRelations")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patent");

                    b.Navigation("PatentClass");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPayment", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentPayments")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patent");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPdf", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentPdFs")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patent");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPriorty", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentPriorties")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPriortyCountry", "PatentPriortyCountry")
                        .WithMany("PatentPriorties")
                        .HasForeignKey("PatentPriortyCountryId");

                    b.Navigation("Patent");

                    b.Navigation("PatentPriortyCountry");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPublication", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentPublications")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPublicationDescription", "PatentPublicationDescription")
                        .WithMany("PatentPublications")
                        .HasForeignKey("PatentPublicationDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patent");

                    b.Navigation("PatentPublicationDescription");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentTransaction", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", "Patent")
                        .WithMany("PatentTransactions")
                        .HasForeignKey("PatentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.PatentTransactionName", "PatentTransactionName")
                        .WithMany("PatentTransactions")
                        .HasForeignKey("PatentTransactionNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patent");

                    b.Navigation("PatentTransactionName");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMark", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", "Attorney")
                        .WithMany("TradeMarks")
                        .HasForeignKey("AttorneyId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecision", "TradeMarkDecision")
                        .WithMany("TradeMarks")
                        .HasForeignKey("TradeMarkDecisionId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriorty", "TradeMarkPriorty")
                        .WithMany("TradeMarks")
                        .HasForeignKey("TradeMarkPriortyId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkStatus", "TradeMarkStatus")
                        .WithMany("TradeMarks")
                        .HasForeignKey("TradeMarkStatusId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkType", "TradeMarkType")
                        .WithMany("Trademarks")
                        .HasForeignKey("TradeMarkTypeId");

                    b.Navigation("Attorney");

                    b.Navigation("TradeMarkDecision");

                    b.Navigation("TradeMarkPriorty");

                    b.Navigation("TradeMarkStatus");

                    b.Navigation("TradeMarkType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecision", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecisionReason", "TradeMarkDecisionReason")
                        .WithMany()
                        .HasForeignKey("TradeMarkDecisionReasonId");

                    b.Navigation("TradeMarkDecisionReason");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriorty", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriortyCountry", "TradeMarkPriortyCountry")
                        .WithMany("TradeMarkPriorties")
                        .HasForeignKey("TradeMarkPriortyCountryId");

                    b.Navigation("TradeMarkPriortyCountry");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkServices", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMark", "TradeMark")
                        .WithMany("TradeMarkServices")
                        .HasForeignKey("TradeMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeMark");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransaction", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMark", "TradeMark")
                        .WithMany("TradeMarkTransaction")
                        .HasForeignKey("TradeMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionDescription", "TradeMarkTransactionDescription")
                        .WithMany("TradeMarkTransactions")
                        .HasForeignKey("TradeMarkTransactionDescriptionId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionName", "TradeMarkTransactionName")
                        .WithMany("TradeMarkTransactions")
                        .HasForeignKey("TradeMarkTransactionNameId");

                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionType", "TradeMarkTransactionType")
                        .WithMany("TradeMarkTransactions")
                        .HasForeignKey("TradeMarkTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeMark");

                    b.Navigation("TradeMarkTransactionDescription");

                    b.Navigation("TradeMarkTransactionName");

                    b.Navigation("TradeMarkTransactionType");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionDetail", b =>
                {
                    b.HasOne("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransaction", "TradeMarkTransaction")
                        .WithMany("TradeMarkTransactionDetails")
                        .HasForeignKey("TradeMarkTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeMarkTransaction");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Attorney", b =>
                {
                    b.Navigation("Designs");

                    b.Navigation("Patents");

                    b.Navigation("TradeMarks");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.AttorneyCompany", b =>
                {
                    b.Navigation("Attorneys");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Design", b =>
                {
                    b.Navigation("DesignerRelations");

                    b.Navigation("DesignProducts");

                    b.Navigation("DesignTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProduct", b =>
                {
                    b.Navigation("DesignProductClassesRelations");

                    b.Navigation("DesignProductImages");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyCountry", b =>
                {
                    b.Navigation("DesignProducts");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignProductPriortyType", b =>
                {
                    b.Navigation("DesignProducts");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignStatus", b =>
                {
                    b.Navigation("Designs");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescription", b =>
                {
                    b.Navigation("DesignTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionDescriptionDetail", b =>
                {
                    b.Navigation("DesignTransactionDescriptions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionType", b =>
                {
                    b.Navigation("DesignTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.DesignTransactionTypeDetail", b =>
                {
                    b.Navigation("DesignTransactionTypes");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Designer", b =>
                {
                    b.Navigation("DesignerRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Holder", b =>
                {
                    b.Navigation("HolderRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Inventor", b =>
                {
                    b.Navigation("InventorRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.LocarnoClass", b =>
                {
                    b.Navigation("DesignProductClassesRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.Patent", b =>
                {
                    b.Navigation("InventorRelations");

                    b.Navigation("PatentClassRelations");

                    b.Navigation("PatentPayments");

                    b.Navigation("PatentPdFs");

                    b.Navigation("PatentPriorties");

                    b.Navigation("PatentPublications");

                    b.Navigation("PatentTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentApplicationType", b =>
                {
                    b.Navigation("Patents");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClass", b =>
                {
                    b.Navigation("PatentClassRelations");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentClassType", b =>
                {
                    b.Navigation("PatentClasses");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPriortyCountry", b =>
                {
                    b.Navigation("PatentPriorties");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentProtectionType", b =>
                {
                    b.Navigation("Patents");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentPublicationDescription", b =>
                {
                    b.Navigation("PatentPublications");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.PatentTransactionName", b =>
                {
                    b.Navigation("PatentTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMark", b =>
                {
                    b.Navigation("TradeMarkServices");

                    b.Navigation("TradeMarkTransaction");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkDecision", b =>
                {
                    b.Navigation("TradeMarks");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriorty", b =>
                {
                    b.Navigation("TradeMarks");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkPriortyCountry", b =>
                {
                    b.Navigation("TradeMarkPriorties");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkStatus", b =>
                {
                    b.Navigation("TradeMarks");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransaction", b =>
                {
                    b.Navigation("TradeMarkTransactionDetails");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionDescription", b =>
                {
                    b.Navigation("TradeMarkTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionName", b =>
                {
                    b.Navigation("TradeMarkTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkTransactionType", b =>
                {
                    b.Navigation("TradeMarkTransactions");
                });

            modelBuilder.Entity("TPHunter.WebServices.Shared.MainData.Core.Models.TradeMarkType", b =>
                {
                    b.Navigation("Trademarks");
                });
#pragma warning restore 612, 618
        }
    }
}
